apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
          - backend:
              serviceName: "{{ include "chart.fullname" . }}"
              servicePort: {{ .Values.service.port }}
            path: /
  tls:
    - hosts:
        - "{{ .Values.ingress.domain }}"
      secretName: {{ include "chart.fullname" . }}
